### ISSUE TITLE
WASM warnings when joining a conference

### ISSUE THREAD

**Issue by slicertech** [voxeet/voxeet-sdk-web#25] opened 2023-11-09 13:04 UTC
Hi,

It seems, everytime we call `await VoxeetSDK.conference.join(conference, joinOptions);` 

joinOptions:
```
constraints: {audio: true, video: false}
preferRecvMono: false
preferSendMono: false
spatialAudio: true
```

we see the below warnings:

`wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
`

`falling back to ArrayBuffer instantiation`

```
if (J(),
    r.instantiateWasm)
        try {
            return r.instantiateWasm(e, t)
        } catch (e) {
            return p("Module.instantiateWasm callback failed with error: " + e),
            !1
        }
    (m || "function" != typeof WebAssembly.instantiateStreaming || te(L) || "function" != typeof fetch ? o(n) : fetch(L, {
            credentials: "same-origin"
        }).then((function(t) {
            return WebAssembly.instantiateStreaming(t, e).then(n, (function(e) {
                return p("wasm streaming compile failed: " + e),
                p("falling back to ArrayBuffer instantiation"),
                o(n)
            }
            ))
        }
```

`failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0`

`Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0)`

Can we get some advice on what this is and the effect this may have?

Thanks.

**Comment by FabienLavocat** [comment] 2023-11-09 15:06
@slicertech where are you loading the wasm files from? (`vsl_impl.wasm`, `dapm_impl.wasm`, `dvdnr.wasm`, `dvwc_impl.wasm`)
This error comes from the web browser preventing the Wed Assembly libraries from being loaded if they were not loaded from a secure / trusted place. In your case, the MIME type of the files that are downloaded must be `application/wasm`. This seems like an update you can make on the backend that serves the files.

**Comment by slicertech** [comment] 2023-11-13 21:02
Hi @FabienLavocat ,
Thanks for the reply.
If I grep for `WASM` in our code base, I find the file here: 

`*/node_modules/@voxeet/voxeet-web-sdk/dist/vsl_impl.wasm`

We serve our react application via AWS S3 and Cloudfront.
I found this guide: https://arne.xyz/2020/08/21/aws-s3-cloudfront-unity3d-webgl/
So I am trying to find where the *.wasm files are hosted.

**Comment by FabienLavocat** [comment] 2023-11-13 22:10
You need to copy all the files from the `dist` folder in your application directory.
If you're using WebPack, here's an example: https://github.com/dolbyio-samples/dolbyio-web-file-presentation-service/blob/main/webpack.config.js#L32C1-L40C12

**Comment by slicertech** [comment] 2023-11-20 21:30
Thanks, @FabienLavocat, I will try this and get back to you. 
We are just waiting for a chance to test our changes.

**Comment by FabienLavocat** [comment] 2023-12-08 16:40
I'm going to close this issue for now, if you still have questions, don't hesitate to reach out.

**Comment by slicertech** [comment] 2023-12-12 13:24
Hi @FabienLavocat ,

Apologies, I just got to test my code. I am still getting the issue.
I copied this: https://github.com/dolbyio-samples/dolbyio-web-file-presentation-service/blob/main/webpack.config.js#L32C1-L40C12

new CopyWebpackPlugin({
        patterns: [
          {
            from: './node_modules/@voxeet/voxeet-web-sdk/dist/dvwc_impl.wasm',
            noErrorOnMissing: true,
          },
          {
            from: './node_modules/@voxeet/voxeet-web-sdk/dist/voxeet-dvwc-worker.js',
            noErrorOnMissing: true,
          },
          {
            from: './node_modules/@voxeet/voxeet-web-sdk/dist/voxeet-worklet.js',
            noErrorOnMissing: true,
          },
          {
            from: './node_modules/@voxeet/voxeet-web-sdk/dist/vsl_impl.bin',
            noErrorOnMissing: true,
          },
          {
            from: './node_modules/@voxeet/voxeet-web-sdk/dist/vsl_impl.wasm',
            noErrorOnMissing: true,
          },
        ],
      }),
      
  Still the same issue.

**Comment by slicertech** [comment] 2023-12-12 14:10
In our build file:

rw-r--r--@  1 jg  staff     5442 12 Dec 13:11 asset-manifest.json
drwxr-xr-x@ 11 jg  staff      352 12 Dec 13:10 customers
-rw-r--r--@  1 jg  staff  2997945 12 Dec 13:11 dvwc_impl.wasm
-rw-r--r--@  1 jg  staff     1047 12 Dec 13:10 favicon.ico
-rw-r--r--@  1 jg  staff    54915 12 Dec 13:10 gamecastsdk-0.1.0.min.js
-rw-r--r--@  1 jg  staff     2118 12 Dec 13:11 index.html
-rw-r--r--@  1 jg  staff    34769 12 Dec 13:10 logo192.png
-rw-r--r--@  1 jg  staff   121199 12 Dec 13:10 logo512.png
-rw-r--r--@  1 jg  staff      504 12 Dec 13:10 manifest.json
-rw-r--r--@  1 jg  staff       67 12 Dec 13:10 robots.txt
drwxr-xr-x@  5 jg  staff      160 12 Dec 13:11 static
-rw-r--r--@  1 jg  staff      933 12 Dec 13:10 videoPlayer.html
-rw-r--r--@  1 jg  staff   176341 12 Dec 13:11 voxeet-dvwc-worker.js
-rw-r--r--@  1 jg  staff    13801 12 Dec 13:11 voxeet-worklet.js
-rw-r--r--@  1 jg  staff   508384 12 Dec 13:11 vsl_impl.bin
-rw-r--r--@  1 jg  staff  1771142 12 Dec 13:11 vsl_impl.wasm

**Comment by FabienLavocat** [comment] 2023-12-12 14:59
Could you please share the Network tab of the web console from Chrome. I'd like to see the failing requests.
Also, make sure your server know the mime type `application/wasm`.

**Comment by slicertech** [comment] 2023-12-13 14:19
<img width="1159" alt="Screenshot 2023-12-13 at 14 14 39" src="https://github.com/voxeet/voxeet-sdk-web/assets/44232622/617d5f9c-56d1-47fc-b86a-88dac9d31015">
<img width="1399" alt="Screenshot 2023-12-13 at 14 14 53" src="https://github.com/voxeet/voxeet-sdk-web/assets/44232622/c99b298b-19f9-4b47-825f-b5b2468f5161">
<img width="1075" alt="Screenshot 2023-12-13 at 14 18 11" src="https://github.com/voxeet/voxeet-sdk-web/assets/44232622/cdab7f64-c2f8-4e76-8d60-b4c88649d9a1">
<img width="1247" alt="Screenshot 2023-12-13 at 14 18 25" src="https://github.com/voxeet/voxeet-sdk-web/assets/44232622/c186e6f3-1af4-4bd4-b692-c8d5b2e39080">

**Comment by slicertech** [comment] 2023-12-13 14:19
Do I need to make server changes?
I found this: https://arne.xyz/2020/08/21/aws-s3-cloudfront-unity3d-webgl/ ?

**Comment by FabienLavocat** [comment] 2023-12-13 15:11
The problem is described in the link you shared.

> .wasm, .wasm.gz or .wasm.br files should be served with a Content-Type: application/wasm response header.

Since you run this website locally (at least in the screenshots), you need to add the mime type to your local computer.

**Comment by slicertech** [comment] 2023-12-13 16:03
I will take a look and get report back

**Comment by slicertech** [comment] 2023-12-15 11:14
![Screenshot 2023-12-15 at 11 12 25](https://github.com/voxeet/voxeet-sdk-web/assets/44232622/836d0828-52af-41ac-84a7-84552f954b69)
![Screenshot 2023-12-15 at 11 13 31](https://github.com/voxeet/voxeet-sdk-web/assets/44232622/8656eb27-c1f6-4d10-9627-ce7aaf4b3f84)
![Screenshot 2023-12-15 at 11 13 39](https://github.com/voxeet/voxeet-sdk-web/assets/44232622/52cd84ff-d8bd-4932-b1cd-5107702f38cc)

**Comment by slicertech** [comment] 2023-12-15 11:15
@FabienLavocat deployed my changes to AWS S3 bucket. As you can see, the files have been copied to the base path.
If I look in AWS, the *.wasm files have the correct content-type.

Thoughts?

**Comment by FabienLavocat** [comment] 2023-12-18 15:43
You should check your network tab, the log entry says that it's not returned as "application/wasm".

**Comment by slicertech** [comment] 2024-01-02 21:37
@FabienLavocat can you tell me where `dapm_impl.wasm` comes from? That looks to be the offending file.
This was not in the list of files to be copied to the base path.

**Comment by FabienLavocat** [comment] 2024-01-02 21:55
https://github.com/voxeet/voxeet-sdk-web/blob/master/dvwc_impl.wasm
The file is in both this GitHub repo and NPM package. You should indeed copy this file to your project (or S3 bucket).

**Comment by slicertech** [comment] 2024-01-03 14:15
Hi @FabienLavocat ,
OK, progress. I added the file above and also moved the files to the correct folder. Now, the WASM files load correctly. I now see this new error :-)

![Screenshot 2024-01-03 at 14 13 36](https://github.com/voxeet/voxeet-sdk-web/assets/44232622/bea01f95-693c-49fd-b6cb-e14cf22fb5f7)
![Screenshot 2024-01-03 at 14 13 46](https://github.com/voxeet/voxeet-sdk-web/assets/44232622/41aae0bb-f546-48b5-a499-10e66156228a)
![Screenshot 2024-01-03 at 14 13 58](https://github.com/voxeet/voxeet-sdk-web/assets/44232622/219ce276-2537-4829-b0e6-e93251be88e1)

Any help here?

**Comment by FabienLavocat** [comment] 2024-01-03 15:34
Do you have this file `audio_dnr.bin` on your S3 storage? Make sure all the files from the NPM package are copied over.

**Comment by slicertech** [comment] 2024-01-03 17:51
Hey @FabienLavocat ,

So all the files in `node_modules/@voxeet/voxeet-web-sdk/dist` should be copied over?

**Comment by FabienLavocat** [comment] 2024-01-03 17:54
Yes

**Comment by slicertech** [comment] 2024-01-03 18:09
@FabienLavocat OK that has fixed most of the issues :-) thanks!

The last warning that shows is:
INFO: Created TensorFlow Lite XNNPACK delegate for CPU. (dapm_impl.wasm?2febc590a084ffcb3bb2bfb2b8da4a15:0x446c6 INFO: Created TensorFlow Lite XNNPACK delegate for CPU.)

I don't think this is an issue.

**Comment by FabienLavocat** [comment] 2024-01-03 18:32
It's an `INFO`, everything is good there.

**Closed as completed by FabienLavocat** 2024-01-03 18:32 UTC
